import Link from 'next/link';
import {notFound} from 'next/navigation';
import {getCurrentSession} from '@/src/modules/identity/application/get-current-session';
import {getOrderForUser,getOrderHistory} from '@/src/modules/orders/infrastructure/supabase-orders';
import {platformConfig} from '@/src/shared/config/platform';
import {runtimeConfig} from '@/src/shared/config/runtime';

function money(locale:string,currency:string,value:number){return new Intl.NumberFormat(locale==='sv'?'sv-SE':'en-GB',{style:'currency',currency,maximumFractionDigits:0}).format(value/100);}
function when(locale:string,value:string|null){if(!value)return '—';return new Intl.DateTimeFormat(locale==='sv'?'sv-SE':'en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value));}
const statusText=(status:string,sv:boolean)=>({PENDING:sv?'Reserverad':'Reserved',PAYMENT_PENDING:sv?'Väntar på betalning':'Awaiting payment',PAID:sv?'Betald':'Paid',FULFILLMENT_PENDING:sv?'Överlämning pågår':'Handoff in progress',COMPLETED:sv?'Affär klar':'Completed',CANCELLED:sv?'Avbruten':'Cancelled',REFUNDED:sv?'Återbetald':'Refunded',DISPUTED:sv?'Tvist':'Disputed'}[status]??status);

export default async function OrderPage({params,searchParams}:{params:Promise<{locale:string;id:string}>,searchParams:Promise<Record<string,string|undefined>>}){
  const {locale,id}=await params; const qs=await searchParams; if(!platformConfig.supportedLocales.includes(locale as 'sv'|'en'))notFound(); const sv=locale==='sv';
  const session=await getCurrentSession(); if(!session||session.preview)notFound(); const order=await getOrderForUser(id,session.user.id); if(!order)notFound();
  const history=await getOrderHistory(id);
  const buyer=order.buyerUserId===session.user.id; const seller=!buyer; const total=money(locale,order.currency,order.totalMinor); const subtotal=money(locale,order.currency,order.subtotalMinor); const fee=money(locale,order.currency,order.platformFeeMinor); const sellerNet=money(locale,order.currency,order.sellerNetMinor);
  const checkoutPossible=buyer&&['PENDING','PAYMENT_PENDING'].includes(order.status);
  const canSchedule=['PAID','FULFILLMENT_PENDING'].includes(order.status)&&order.fulfillmentMethod==='LOCAL_HANDOFF';
  const canSellerConfirm=seller&&order.status==='FULFILLMENT_PENDING'&&!order.sellerConfirmedAt;
  const canBuyerConfirm=buyer&&order.status==='FULFILLMENT_PENDING'&&!order.buyerConfirmedAt;
  return <main className="accountShell orderDetailShell"><div className="accountTop"><Link href={`/${locale}/orders`}>← {sv?'Mina affärer':'My orders'}</Link><span className={`statusPill status-${order.status.toLowerCase()}`}>{statusText(order.status,sv)}</span></div>
    {qs.reserved&&<div className="authNotice success">{sv?'Varan är reserverad. Slutför betalningen för att säkra köpet.':'The item is reserved. Complete payment to secure the purchase.'}</div>}
    {qs.cancelled&&<div className="authNotice">{sv?'Affären har avbrutits och annonsen är aktiv igen.':'The order was cancelled and the listing is active again.'}</div>}
    {qs.payment==='success'&&<div className="authNotice success">{sv?'Betalningen är skickad. Status uppdateras automatiskt när Stripe bekräftar den.':'Payment submitted. Status updates automatically after Stripe confirms it.'}</div>}
    {qs.payment==='cancelled'&&<div className="authNotice">{sv?'Du avbröt betalningen. Reservationen ligger kvar tills den avbryts eller betalningen slutförs.':'You cancelled checkout. The reservation remains until cancelled or paid.'}</div>}
    {qs.payment==='setup'&&<div className="authNotice">{sv?'Livebetalning är ännu inte aktiverad i Repassing-miljön.':'Live payments are not enabled in this Repassing environment yet.'}</div>}
    {qs.payment==='seller_setup'&&<div className="authNotice">{sv?'Säljaren måste slutföra sitt utbetalningskonto innan betalning kan tas emot.':'The seller must complete payout setup before payment can be accepted.'}</div>}
    {qs.payment==='error'&&<div className="formError">{sv?'Checkout kunde inte startas. Försök igen senare.':'Checkout could not be started. Try again later.'}</div>}
    {qs.handoff==='updated'&&<div className="authNotice success">{sv?'Överlämningen har uppdaterats.':'Handoff updated.'}</div>}
    {qs.handoff==='completed'&&<div className="authNotice success">{sv?'Affären är klar. Återanvändningen har registrerats.':'The order is complete. The reuse has been registered.'}</div>}
    {qs.handoff==='error'&&<div className="formError">{sv?'Överlämningen kunde inte uppdateras.':'The handoff could not be updated.'}</div>}
    <section className="orderDetailCard">{order.imageUrl?<img className="orderDetailImage" src={order.imageUrl} alt=""/>:<div className="orderDetailImage orderImageFallback">RE</div>}<div><span className="eyebrow">{buyer?(sv?'DU KÖPER':'YOU BUY'):(sv?'DU SÄLJER':'YOU SELL')}</span><h1>{order.title}</h1><strong className="detailPrice">{total}</strong>
      <dl className="detailFacts"><div><dt>{sv?'Annonspris':'Listing price'}</dt><dd>{subtotal}</dd></div>{order.platformFeeMinor>0&&<div><dt>{sv?'Repassing-avgift':'Repassing fee'}</dt><dd>{fee}</dd></div>} {!buyer&&<div><dt>{sv?'Till säljaren':'Seller proceeds'}</dt><dd>{sellerNet}</dd></div>}<div><dt>Status</dt><dd>{statusText(order.status,sv)}</dd></div><div><dt>{sv?'Överlämning':'Fulfillment'}</dt><dd>{order.fulfillmentMethod==='LOCAL_HANDOFF'?(sv?'Lokal överlämning':'Local handoff'):(order.fulfillmentMethod??'—')}</dd></div></dl>
      {checkoutPossible&&<form method="post" action={`/api/v1/orders/${order.id}/checkout`} className="checkoutBox"><input type="hidden" name="locale" value={locale}/><button className="primary checkoutButton" type="submit">{order.status==='PAYMENT_PENDING'?(sv?'Fortsätt till betalning':'Continue to payment'):(sv?'Betala säkert':'Pay securely')}</button><small>{runtimeConfig.payments.mode==='stripe'?(sv?'Betalningen hanteras av Stripe. Repassing behåller sin avgift och resten går till säljaren.':'Payment is handled by Stripe. Repassing keeps its fee and the remainder goes to the seller.'):(sv?'Betalningsarkitekturen är klar men livebetalning är ännu inte aktiverad.':'Payment architecture is ready, but live payments are not enabled yet.')}</small></form>}

      {canSchedule&&<section className="handoffPanel"><span className="eyebrow">{sv?'ÖVERLÄMNING':'HANDOFF'}</span><h2>{sv?'Bestäm när och var':'Set time and place'}</h2><form method="post" action={`/api/v1/orders/${order.id}/handoff`} className="handoffForm"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="action" value="SCHEDULE"/><label>{sv?'Plats':'Location'}<input name="handoff_location" defaultValue={order.handoffLocation??''} placeholder={sv?'t.ex. efter träningen':'e.g. after practice'}/></label><label>{sv?'Tid':'Time'}<input name="scheduled_at" type="datetime-local" defaultValue={order.scheduledAt?new Date(order.scheduledAt).toISOString().slice(0,16):''}/></label><button className="secondary" type="submit">{order.scheduledAt?(sv?'Uppdatera överlämning':'Update handoff'):(sv?'Boka överlämning':'Schedule handoff')}</button></form>{(order.scheduledAt||order.handoffLocation)&&<p className="handoffSummary"><strong>{sv?'Planerat':'Scheduled'}:</strong> {when(locale,order.scheduledAt)}{order.handoffLocation?` · ${order.handoffLocation}`:''}</p>}</section>}

      {order.status==='FULFILLMENT_PENDING'&&<section className="confirmationPanel"><span className="eyebrow">{sv?'BEKRÄFTA ÖVERLÄMNING':'CONFIRM HANDOFF'}</span><div className="confirmationGrid"><div className={order.sellerConfirmedAt?'confirmDone':''}><strong>{sv?'Säljare':'Seller'}</strong><span>{order.sellerConfirmedAt?(sv?'✓ Överlämnad':'✓ Handed over'):(sv?'Väntar':'Waiting')}</span></div><div className={order.buyerConfirmedAt?'confirmDone':''}><strong>{sv?'Köpare':'Buyer'}</strong><span>{order.buyerConfirmedAt?(sv?'✓ Mottagen':'✓ Received'):(sv?'Väntar':'Waiting')}</span></div></div>{canSellerConfirm&&<form method="post" action={`/api/v1/orders/${order.id}/handoff`}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="action" value="SELLER_CONFIRM"/><button className="primary" type="submit">{sv?'Jag har lämnat över varan':'I handed over the item'}</button></form>}{canBuyerConfirm&&<form method="post" action={`/api/v1/orders/${order.id}/handoff`}><input type="hidden" name="locale" value={locale}/><input type="hidden" name="action" value="BUYER_CONFIRM"/><button className="primary" type="submit">{sv?'Jag har fått varan':'I received the item'}</button></form>}<small>{sv?'Affären slutförs automatiskt när båda har bekräftat.':'The order completes automatically when both sides confirm.'}</small></section>}

      {order.status==='COMPLETED'&&<section className="completedPanel"><strong>✓ {sv?'Affären är klar':'Order completed'}</strong><p>{sv?'Varan har fått en ny användare och registrerats i Repassings återanvändningsstatistik.':'The item has a new user and has been registered in Repassing reuse statistics.'}</p><Link className="secondary inlineAction receiptLink" href={`/${locale}/orders/${order.id}/receipt`}>{sv?'Visa affärskvitto':'View transaction receipt'}</Link></section>}

      <div className="orderActions">{order.conversationId&&<Link className="primary inlineAction" href={`/${locale}/messages/${order.conversationId}`}>{sv?'Öppna meddelanden':'Open messages'}</Link>}<Link className="secondary inlineAction" href={`/${locale}/listings/${order.listingId}`}>{sv?'Visa annons':'View listing'}</Link></div>
      {['PENDING','PAYMENT_PENDING'].includes(order.status)&&<form className="dangerZone" method="post" action={`/api/v1/orders/${order.id}/cancel`}><input type="hidden" name="locale" value={locale}/><button className="dangerButton" type="submit">{sv?'Avbryt reservation':'Cancel reservation'}</button></form>}
    </div></section>
    {history.length>0&&<section className="orderTimeline"><span className="eyebrow">{sv?'ORDERHISTORIK':'ORDER HISTORY'}</span><h2>{sv?'Vad som hänt':'What happened'}</h2>{history.map(item=><div className="timelineItem" key={item.id}><span className="timelineDot"/><div><strong>{statusText(item.toStatus,sv)}</strong><small>{when(locale,item.createdAt)}</small></div></div>)}</section>}
  </main>;
}
